{% set name = "vegafusion-python-embed" %}
{% set name_under = "vegafusion_python_embed" %}
{% set version = "1.6.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name_under[0] }}/{{ name_under }}/{{ name_under }}-{{ version }}.tar.gz
  sha256: 22262c3064105fab1d7a4108ad4bce7e8156d5036994c19c01faf98029a430d0

build:
  number: 0
  script: |
    cargo-bundle-licenses --format yaml --output THIRDPARTY.yml
    {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - {{ compiler('c') }}        # [not win]
    - {{ compiler('m2w64_c') }}  # [win]
    - {{ compiler('rust') }}
    - python                              # [build_platform != target_platform]
    - cross-python_{{ target_platform }}  # [build_platform != target_platform]
    - crossenv                            # [build_platform != target_platform]
    - maturin                             # [build_platform != target_platform]
    - protobuf
    - cargo-bundle-licenses
  host:
    - python
    - pip
    - maturin
  run:
    - python

test:
  imports:
    - vegafusion_embed
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://vegafusion.io
  license: BSD-3-Clause
  license_family: BSD
  license_file:
    - LICENSE
    - THIRDPARTY.yml

  summary: Server-side acceleration for the Vega visualization grammar
  description: |
    VegaFusion provides serverside acceleration for the Vega visualization grammar. The vegafusion-python-embed
    package is generally used as a dependency of higher-level, pure-Python, packages like vegafusion-jupyter.
  doc_url: https://vegafusion.io
  dev_url: https://github.com/hex-inc/vegafusion

extra:
  recipe-maintainers:
    - dhirschfeld
    - jonmmease
