{% set name = "vegafusion-python-embed" %}
{% set name_under = "vegafusion_python_embed" %}
{% set version = "1.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name_under[0] }}/{{ name_under }}/{{ name_under }}-{{ version }}.tar.gz
  sha256: a178dead3e676f701e5e0ea5df988811590f675d62d75cbcf6380aa45120dc05

build:
  number: 0
  script: |
    cargo-bundle-licenses --format yaml --output THIRDPARTY.yml
    {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - {{ compiler('c') }}        # [not win]
    - {{ compiler('m2w64_c') }}  # [win]
    - {{ compiler('rust') }}
    - protobuf
    - cargo-bundle-licenses
  host:
    - python
    - pip
    - maturin
  run:
    - python

test:
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://vegafusion.io
  license: AGPL-3.0-or-later
  license_family: GPL
  license_file:
    - LICENSE
    - THIRDPARTY.yml

  summary: Server-side acceleration for the Vega visualization grammar
  description: |
    VegaFusion provides serverside acceleration for the Vega visualization grammer. The vegafusion-python-embed
    package is generally used as a dependency of higher-level, pure-Python, packages like vegafusion-jupyter.
  doc_url: https://vegafusion.io
  dev_url: https://github.com/vegafusion/vegafusion

extra:
  recipe-maintainers:
    - dhirschfeld
    - jonmmease
